language: android
android:
before_install:
    - android update sdk --no-ui --all --filter build-tools-26.0.2,android-26,extra-android-m2repository
    - mkdir -p "/usr/local/android-sdk/licenses"
    - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "/usr/local/android-sdk/licenses/android-sdk-license"
    - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$/usr/local/android-sdk/licenses/android-sdk-preview-license"
    - cd  ScreenRotation

jdk: oraclejdk8
licenses:
    - android-sdk-license-.+
    - '.+'

script:
    - chmod +x gradlew
    - ./gradlew testDebug 
