language: android
android:
 components:
    - tools
    - build-tools-25.0.2
    - android-25


before_install:
    - cd  StopWatch
jdk: oraclejdk8
script:
    - chmod +x gradlew
    - ./gradlew testDebug 
