language: android
android:
before_install:
    - cd  ScreenRotation
    - $ANDROID_HOME/tools/bin/sdkmanager --licenses

jdk: oraclejdk8
licenses:
    - android-sdk-license-.+
    - '.+'

script:
    - chmod +x gradlew
    - ./gradlew testDebug 
