language: android
android:
before_install:
    - cd  ScreenRotation
    - yes | sdkmanager --licenses

jdk: oraclejdk8
licenses:
    - android-sdk-license-.+
    - '.+'

script:
    - chmod +x gradlew
    - ./gradlew testDebug 
