language: android
android:
before_install:
    - cd  ScreenRotation
    - cd
    - cd $ANDROID_HOME/tools/bin/
    - ./sdkmanager --licenses
    - cd

jdk: oraclejdk8
licenses:
    - android-sdk-license-.+
    - '.+'

script:
    - chmod +x gradlew
    - ./gradlew testDebug 
